---
- name: yum packaged requirements 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - libXrender
  - xorg-x11-server-Xvfb
  - xorg-x11-fonts-Type1 
  - xorg-x11-fonts-75dpi
  - pandoc
  - zip
